[tool.poetry]
name = "qualibrate-core"
version = "0.1.0"
description = ""
authors = ["Serwan Asaad <serwan.asaad@quantum-machines.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
