[tool.poetry]
name = "qualibrate-core"
version = "0.1.0"
description = ""
authors = ["Serwan Asaad <serwan.asaad@quantum-machines.co>"]
readme = "README.md"
packages = [{ include = "qualibrate" }]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^2.7.3"


[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.4.8"

[tool.ruff]
line-length = 80
target-version = "py39"

[tool.ruff.lint]
extend-select = ["I"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
